import Commands.help
import Commands.about
import Commands.user
import Commands.avatar
import Commands.eval
import Commands.eightball
import Commands.rngen
import Commands.guild
import Commands.calc
import Commands.settings
import Commands.publish
import Commands.ping
import Commands.weather
import Commands.wiki
import Commands.codec
